# Generated by Django 3.0.4 on 2020-03-07 12:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=50)),
                ('content_type', models.CharField(choices=[('V', 'Video'), ('I', 'Image'), ('A', 'Audio')], default=('V', 'Video'), max_length=5)),
                ('content_language', models.CharField(choices=[('TR', 'Turkish'), ('EN', 'English'), ('FR', 'French')], default=('TR', 'Turkish'), max_length=7)),
                ('content_sex', models.CharField(choices=[('M', 'Man'), ('W', 'Women')], default=('M', 'Man'), max_length=5)),
                ('content_emotion', models.CharField(choices=[('neutral', 'Neutral'), ('calm', 'Calm'), ('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fearful', 'Fearful'), ('disgust', 'Disgust'), ('surprised', 'Suprised')], default=('neutral', 'Neutral'), max_length=9)),
                ('commend', models.TextField()),
                ('content_upload', models.FileField(upload_to='')),
                ('uploader', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
